[tool.uv]
dev-dependencies = []

[project]
name = "minimind"
version = "0.1.0"
description = "MiniMind: lightweight LLM training/inference utilities"
readme = "README.md"
requires-python = ">=3.10,<3.13"
license = { file = "LICENSE" }
authors = [
  { name = "MiniMind Maintainers" }
]
dependencies = [
  "datasets>=2.15.0",
  "datasketch==1.6.4",
  "Flask==3.0.3",
  "Flask-Cors==4.0.0",
  "jieba==0.42.1",
  "jsonlines==4.0.0",
  "marshmallow==3.22.0",
  "matplotlib>=3.5.0",
  "ngrok==1.4.0",
  "nltk==3.8",
  "numpy>=1.24.0,<2.0.0",
  "openai>=1.50.0",
  "pandas>=1.5.0,<3.0.0",
  "peft>=0.7.0,<1.0.0",
  "psutil==5.9.8",
  "pydantic>=2.5.0,<3.0.0",
  "rich==13.7.1",
  "scikit-learn==1.5.1",
  "sentence-transformers>=2.2.0",
  "simhash==2.1.2",
  "tiktoken==0.5.1",
  "transformers>=4.40.0,<5.0.0",
  "jinja2==3.1.2",
  "trl>=0.12.0,<1.0.0",
  "ujson==5.1.0",
  "wandb>=0.17.0",
  "streamlit>=1.28.0",
  "torch>=2.6.0",
  "torchvision>=0.21.0",
]

[project.urls]
homepage = "https://github.com/"

# Mac-specific PyTorch configuration (no CUDA)
[tool.uv.sources]
torch = { index = "pytorch" }
torchvision = { index = "pytorch" }

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu"

[tool.hatch.build.targets.wheel]
packages = ["model", "dataset", "trainer", "scripts"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
